source 'https://github.com/CocoaPods/Specs.git'

#platform :ios, '10.0'
platform :ios, '13.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'GoWild' do

  pod 'R.swift', '5.0.0'
  pod 'netfox'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'PhoneNumberKit'
  pod 'SVPinView', '~> 1.0'
  pod 'Cosmos', '~> 23.0'
  pod 'IQDropDownTextField'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  #pod 'Firebase/DynamicLinks'
  pod 'GoogleSignIn'
  pod 'ObjectMapper', '~> 3.5'
  pod 'YPImagePicker'
  pod 'Kingfisher', '~> 7.0'
  pod 'PKHUD', '~> 5.0'
  pod 'JGProgressHUD'
  pod 'TOCropViewController'
  pod 'MessageKit'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'GoogleMaps', '7.3.0'
  pod 'GooglePlaces', '7.2.0'
  pod 'Lightbox'
  pod 'NotificationView'
  pod 'MapboxMaps', '10.14.0'
  pod 'Polyline', '~> 5.0'
#  pod 'OTPFieldView', '1.0.1'
#  pod 'SwiftLint', '0.31.0'

  target 'GoWildTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
