name: gowild_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.7
  provider: ^6.0.2
  google_fonts: ^2.3.1
  intl_phone_field: ^3.1.0
  flutter_verification_code: ^1.1.2+1
  google_maps_flutter: ^2.1.3
  location: ^4.3.0
  sliding_up_panel: ^2.0.0+1
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  flutter_map: ^0.14.0
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.0.9
  google_maps_routes: ^1.1.2
  shared_preferences: ^2.0.15
  html: ^0.15.0
  flutter_map_tappable_polyline: ^3.1.0
  latlong2: ^0.8.1
  google_sign_in: ^5.3.0
  flutter_svg: ^1.0.3
  dio: ^4.0.6
  easy_geofencing: ^0.2.0
  flutter_animarker: ^3.2.0
  flutter_geofence: ^0.4.4
  #  flutter_background_geolocation: ^4.6.2
  expandable: ^5.0.1
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  flutter_local_notifications: ^9.5.2
  flutter_login_facebook: ^1.5.0+1
  adaptive_dialog: ^1.6.2+1
  geofence_service: ^3.4.8
  flutter_launcher_icons: ^0.9.3



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/android/192x192.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/pngs/
    - assets/images/svgs/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TheForegenRegular
      fonts:
        - asset: assets/fonts/foregenregular.ttf
    - family: TheForegenRoughOne
      fonts:
        - asset: assets/fonts/TheForegenRoughOne.ttf

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
